yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import DateAbstractModel

User = get_user_model()


class Post(DateAbstractModel):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(
        'Название группы',
        help_text='Введите название группы',
        max_length=200
    )
    slug = models.SlugField(
        'Адрес для группы',
        unique=True,
        help_text=(
            'Укажите уникальный адрес для группы. '
            'Используйте только латиницу, цифры, '
            'дефисы и знаки подчёркивания'
        )
    )
    description = models.TextField(
        'Описание группы',
        help_text='Введите описание группы',
    )

    def __str__(self):
        return self.title


class Comment(DateAbstractModel):
    post = models.ForeignKey(
        Post,
        verbose_name='Пост',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор комментария',
        related_name='comments'
    )
    text = models.TextField('Комментарий', max_length=200)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор канала',
        related_name='following'
    )

    def __str__(self):
        return f'Пользователь "{self.user}" подписан на "{self.author}"'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

COUNT_DISPLAYED_OBJECTS = 10


def index(request):
    posts = Post.objects.order_by('-created')
    paginator = Paginator(posts, COUNT_DISPLAYED_OBJECTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': 'Последние обновления на сайте',
    }
    return render(request, 'posts/index.html', context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.order_by('-created')
    paginator = Paginator(posts, COUNT_DISPLAYED_OBJECTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    profile_posts = user.posts.order_by('-created')
    paginator = Paginator(profile_posts, COUNT_DISPLAYED_OBJECTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = request.user.is_authenticated and (
        user.following.filter(user=request.user)
    )
    context = {
        'page_obj': page_obj,
        'author': user,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post_count = post.author.posts.count()
    comments = post.comments.order_by('-created')
    context = {
        'form': CommentForm(),
        'comments': comments,
        'post': post,
        'post_count': post_count,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user == post.author:
        template = 'posts/create_post.html'
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post
        )
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)

        return render(request, template, {'form': form, 'is_edit': True})

    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    user_follows_posts = Post.objects.filter(
        author__following__user=request.user
    ).order_by('-created')
    paginator = Paginator(user_follows_posts, COUNT_DISPLAYED_OBJECTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': 'Мои подписки',
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author.username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if Follow.objects.filter(user=request.user, author=author).exists():
        Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', author.username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
  {% if is_edit %} 
    Редактировать запись
  {% else %}
    Новый пост
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %} 
              Редактировать запись
            {% else %}
              Новый пост
            {% endif %}           
          </div>
          <div class='card-body'>
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
            >
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 py-3"
                  {% if field.field.required %} 
                    aria-required="true"
                  {% else %}
                    aria-required="false"
                  {% endif %}
                >
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                    {{ field|addclass:'form-control' }}
                      {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %} 
                    Сохранить
                  {% else %}
                    Добавить
                {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <h1>{{ title }}</h1>
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
        <article>
            <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
                Дата публикации: {{ post.created|date:"j E Y, H : i" }}
            </li>
            </ul>
            {% thumbnail post.image "1600x900" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
            {{ post.text }}
            </p>
            <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
        </article>
    {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы "{{ post.group }}"</a>
    {% endif %} 
    {% if not forloop.last %}
        <hr>
    {% endif %}
    {% endfor %}
  </div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock title %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
      <p>
        {{ group.description }}
      </p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: 
            <a href="{% url 'posts:profile' post.author.username %}">
              {{ post.author.get_full_name }}
            </a>
          </li>
          <li>
            Дата публикации: {{ post.created|date:"j E Y, H : i" }}
          </li>
        </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}      
        <p>
          {{ post.text }}
        </p>         
      </article>
      <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %} 
  </div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block content %}
{% load thumbnail %}
{% load cache %}
{% cache 20 index_page %}
  <div class="container py-5">
    <h1>{{ title }}</h1>
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author.username }}{% endif %}
          </li>
          <li>
            Дата публикации: {{ post.created|date:"j E Y, H : i" }}
          </li>
        </ul>
        {% thumbnail post.image "1300x700" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
      </article>
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы "{{ post.group }}"</a>
      {% endif %} 
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  </div>
{% endcache %}
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock title %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.created|date:"j E Y, H : i" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <p>
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </p>
            </li>
          {% endif %}
            <li class="list-group-item">
              Автор: 
              <a href="{% url 'posts:profile' post.author.username %}">
                {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author.username }}{% endif %}
              </a>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post_count }}</span>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
          {% if user.username == post.author.username %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              Редактировать запись
            </a>
          {% endif %}
          {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %}
      </article>
    </div> 
  </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock title %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {% if author.get_full_name %}{{ author.get_full_name }}{% else %}{{ author.username }}{% endif %}</h1>
        {% include 'includes/switcher.html' %}
          <h3>Всего постов: {{ author.posts.count }}</h3>
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
      {% endif %}
    </div>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.created|date:"j E Y, H : i" }}
          </li>
        </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      </article>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }}</a>
        {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  </div>
{% endblock content %} 